### ISSUE TITLE
default $IFS is not `unset`

### ISSUE THREAD

**Issue by chino** [p8952/bocker#18]
Note in `bocker_pull` there is a call to manipulate `$IFS` and then an attempt to revert it by using `unset IFS` however the default `$IFS` is actually `$' \n\t'`.  Unsetting `$IFS` like that I believe will globally affect white space splitting.

```
~ $ [[ $IFS == $' \t\n' ]] && echo true
true
~ $ read a b <<< "1 2"; echo $a
1
~ $ IFS='' read a b <<< "1 2"; echo $a
1 2
```

**Comment by p8952** [comment]
Thanks, sorted in 4956a537b75d2217ae8bcca7057acc22f6977722
